### ISSUE TITLE
open-brace character { is rendered as {'{'} in Markdown code blocks

### ISSUE THREAD

**Issue by kevinworth** [grommet/grommet-markdown-loader#2]
Filed originally as OpenSwitch bug https://tree.taiga.io/project/openswitch/issue/1318

Braces in backticks, such as [here](http://www.openswitch.net/documents/dev/changing-openswitch-code#directory-structure-of-the-deployed-nfs-directory) with Markdown source [here](http://git.openswitch.net/cgit/openswitch/ops-docs/tree/changing-openswitch-code.md#n702) render correctly, indicating it's not EVERY brace, just ones in code blocks.

This could be a misconfiguration or a misbehaving script within OpenSwitch infrastructure, but seems oddly specific; checking to see if this could be an upstream issue.

**Comment by kevinworth** [comment]
Appears this might have been introduced with https://github.com/grommet/grommet-markdown-loader/commit/98aa0182011e0feaa110229ff9ffde65906a09a0

**Comment by kevinworth** [comment]
Best guess is this is related to the replace happening in https://github.com/grommet/grommet-markdown-loader/blob/master/index.js#L24 (similar one occurs in https://github.com/grommet/grommet-markdown-loader/blob/master/index.js#L29 )

**Comment by alansouzati** [comment]
Good catch, this seems not to be required anymore using the latest version of React (15.0
![screen shot 2016-06-10 at 12 34 15 pm](https://cloud.githubusercontent.com/assets/1207250/15976458/baa9303e-2f07-11e6-99d0-fe0f11b51abc.png)
)

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet-markdown-loader/commit/68209140f0f6ba5191190fbe3aab4a0286dbc5f6

Will soon release `0.3.0` as this could be a breaking change for those using React < 15

**Comment by alansouzati** [comment]
0.3.0 released with both fixes. https://www.npmjs.com/package/grommet-markdown-loader

Please update to the latest react when you update to 0.3.0
